/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "off-white": "#F5F5F2",
        "carbon-gray": "#1A1A1C",
        "primary-fixed": "#dce1ff",
        "tertiary-container": "#81000c",
        "surface-variant": "#353436",
        "on-secondary-fixed": "#1b1b1d",
        "primary-fixed-dim": "#b5c4ff",
        "on-secondary-container": "#b7b4b7",
        "surface": "#131314",
        "on-primary": "#00287d",
        "surface-container-highest": "#353436",
        "on-tertiary": "#680008",
        "surface-container-lowest": "#0e0e0f",
        "secondary-container": "#474649",
        "on-primary-fixed-variant": "#153ea3",
        "on-background": "#e5e2e3",
        "inverse-on-surface": "#313031",
        "surface-container-low": "#1c1b1c",
        "primary-container": "#003399",
        "inverse-surface": "#e5e2e3",
        "race-red": "#D5001C",
        "on-tertiary-container": "#ff847a",
        "error-container": "#93000a",
        "matte-black": "#0A0A0B",
        "background": "#131314",
        "primary": "#b5c4ff",
        "outline": "#8e909e",
        "on-tertiary-fixed-variant": "#930010",
        "liquid-blue": "#003399",
        "frozen-white": "#F0F2F5",
        "shadow-black": "#111214",
        "on-tertiary-fixed": "#410003",
        "surface-dim": "#131314",
        "on-surface": "#e5e2e3",
        "on-secondary": "#303032",
        "inverse-primary": "#3557bc",
        "tertiary-fixed-dim": "#ffb3ac",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "surface-bright": "#3a393a",
        "secondary-fixed-dim": "#c8c6c8",
        "surface-container-high": "#2a2a2b",
        "surface-container": "#201f20",
        "on-error": "#690005",
        "tertiary-fixed": "#ffdad6",
        "secondary-fixed": "#e4e2e4",
        "on-surface-variant": "#c4c5d5",
        "tertiary": "#ffb3ac",
        "surface-tint": "#b5c4ff",
        "on-primary-fixed": "#00164e",
        "secondary": "#c8c6c8",
        "on-secondary-fixed-variant": "#474649",
        "outline-variant": "#444653",
        "on-primary-container": "#8aa4ff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "32px",
        "unit": "8px",
        "margin-desktop": "80px",
        "margin-mobile": "24px",
        "container-max": "1440px"
      },
      "fontFamily": {
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Archivo Narrow", "sans-serif"],
        "display-xl": ["Archivo Narrow", "sans-serif"],
        "headline-lg": ["Archivo Narrow", "sans-serif"],
        "label-bold": ["Archivo Narrow", "sans-serif"],
        "eyebrow-caps": ["Archivo Narrow", "sans-serif"]
      },
      "fontSize": {
        "body-md": ["18px", {"lineHeight": "160%", "fontWeight": "400"}],
        "body-sm": ["15px", {"lineHeight": "150%", "fontWeight": "400"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "110%", "fontWeight": "600"}],
        "display-xl": ["96px", {"lineHeight": "100%", "letterSpacing": "-0.04em", "fontWeight": "700"}],
        "headline-lg": ["48px", {"lineHeight": "110%", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-bold": ["12px", {"lineHeight": "100%", "letterSpacing": "0.1em", "fontWeight": "700"}],
        "eyebrow-caps": ["14px", {"lineHeight": "100%", "letterSpacing": "0.4em", "fontWeight": "600"}]
      }
    }
  },
  plugins: [],
}
